### ISSUE TITLE
Docker利用時の生成物の所有者がrootになる

### ISSUE THREAD

**Issue by primenumber** [windymelt/zmm#30]
Linux環境だと、rootless modeでないときは生成物の所有者がrootになってしまい、取り回しが若干面倒になります。
Dockerfileでユーザーを作成してそのuid/gidをホスト環境に合わせるなどの何らかの方法で回避したいです。
cf. https://zenn.dev/anyakichi/articles/73765814e57cba

**Comment by windymelt** [comment]
いかにも良さそう。自分もたまに悩まされていたのでなんとかしたい（プルリクも歓迎です）。

**Comment by windymelt** [comment]
fixed
